// Capturas del manual de usuario (docs/manual/img, 1440×900) contra un servidor completo con cuentas.
// Uso: PORT=4193 DATA_DIR=/tmp/alldraw-data STATIC_DIR=<dist> node apps/server/src/server.mjs && BASE=http://127.0.0.1:4193 node e2e/manual-shots.mjs
import { chromium } from 'playwright-core';
const base = process.env.BASE ?? 'http://127.0.0.1:4193';
const out = new URL('../docs/manual/img/', import.meta.url).pathname;
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const shot = (n) => page.screenshot({ path: `${out}/${n}.png` });
const wait = (ms) => page.waitForTimeout(ms);
await page.goto(base + '/#/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /Entrar \/ registrarse/ }).waitFor();
await shot('01-inicio');
await page.getByRole('button', { name: /Entrar \/ registrarse/ }).click();
await page.getByRole('button', { name: 'No tengo cuenta' }).click();
await page.locator('input[type=email]').fill('ana@ejemplo.com');
await page.locator('.field input:not([type=email]):not([type=password])').fill('Ana');
await page.locator('input[type=password]').fill('contraseña-larga');
await wait(200);
await shot('02-entrar');
await page.getByRole('button', { name: 'Registrarme' }).click();
await page.waitForSelector('text=En el servidor', { timeout: 15000 });
await page.getByRole('button', { name: /Abrir la demo/ }).click();
await page.waitForURL(/#\/s\//, { waitUntil: 'commit' });
await page.waitForSelector('.react-flow__node', { timeout: 20000 }); await wait(1500);
await shot('03-editor-archimate');
await page.locator('.react-flow__node', { hasText: 'Alta de cliente' }).first().dblclick(); await wait(900);
await shot('04-bpmn-detalle');
await page.locator('.react-flow__node', { hasText: 'Verificar identidad' }).first().click({ button: 'right' });
await page.waitForSelector('.ad-menu'); await wait(300);
await shot('05-menu-dimension');
await page.keyboard.press('Escape');
await page.locator('.ad-views__item', { hasText: 'Alta de cliente · Estados' }).first().click(); await wait(800);
await shot('06-estados');
await page.locator('.ad-views__item', { hasText: 'Mapa capas' }).first().click(); await wait(900);
await page.locator('.react-flow__node', { hasText: 'clientes-api' }).first().click(); await wait(300);
await page.getByRole('button', { name: /Pines/ }).click(); await wait(400);
await shot('07-rejilla-pines');
await page.locator('.ad-problems__bar').click(); await wait(400);
await shot('08-problemas');
await page.locator('.ad-problems__bar').click(); await wait(200);
await page.getByRole('button', { name: 'Espacio' }).click(); await wait(500);
await page.locator('.ad-ws-tabs button', { hasText: 'Reglas' }).click(); await wait(400);
await shot('09-espacio-reglas');
await page.keyboard.press('Escape'); await wait(300);
await page.getByRole('button', { name: 'Compartir' }).click();
await page.getByRole('button', { name: 'Nuevo enlace de edición' }).click();
await page.getByRole('button', { name: 'Nuevo enlace de lectura' }).click();
await page.waitForSelector('text=lectura', { timeout: 10000 }); await wait(500);
await shot('10-compartir');
await page.keyboard.press('Escape'); await wait(300);
await page.getByRole('button', { name: /Importar \/ Exportar/ }).click();
await page.waitForSelector('[role="menu"]'); await wait(300);
await shot('11-importar-exportar');
await page.keyboard.press('Escape');
await page.goto(base + '/#/keys', { waitUntil: 'networkidle' });
await page.locator('#key-name').fill('agente-claude');
await page.getByRole('button', { name: 'Crear' }).click(); await wait(800);
await shot('12-claves-api');
await browser.close();
console.log('ok');
