// Enlace de lectura: el servidor descarta las escrituras del viewer y la interfaz queda en solo lectura.
import { chromium } from 'playwright-core';
const base = process.env.BASE ?? 'http://127.0.0.1:4002';
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
const mk = async () => (await browser.newContext()).newPage();
const a = await mk();
await a.goto(base + '/#/', { waitUntil: 'networkidle' });
const email = `ro-${Date.now()}@test.local`;
await a.getByRole('button', { name: /Entrar/ }).click();
await a.getByRole('button', { name: 'No tengo cuenta' }).click();
await a.locator('input[type=email]').fill(email);
await a.locator('.field input:not([type=email]):not([type=password])').fill('RO');
await a.locator('input[type=password]').fill('contraseña-larga');
await a.getByRole('button', { name: 'Registrarme' }).click();
await a.waitForSelector('text=En el servidor', { timeout: 15000 });
await a.getByRole('button', { name: /Abrir la demo/ }).click();
await a.waitForURL(/#\/s\//, { waitUntil: 'commit' }); await a.waitForSelector('.react-flow__node', { timeout: 20000 });
const wsId = /#\/s\/([^/?]+)/.exec(a.url())[1];
const link = await a.evaluate(async id => (await fetch(`/api/workspaces/${id}/links`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ role: 'viewer' }) })).json(), wsId);
const b = await mk();
await b.goto(link.url.replace(/^https?:\/\/[^/]+/, base), { waitUntil: 'networkidle' });
await b.waitForSelector('.react-flow__node', { timeout: 20000 }); await b.waitForTimeout(800);
console.log('ro nodes:', await b.locator('.react-flow__node').count(), '| palette:', await b.locator('.ad-pal').count(), '| status:', await b.locator('.app-status').first().innerText());
await browser.close();
